### ISSUE TITLE
Upgrade to ECOS 2.0.5

### ISSUE THREAD

**Issue by SteveDiamond** [embotech/ecos-python#11]
Could the Python interface be upgraded to ECOS 2.0.5?

**Comment by wkschwartz** [comment]
Will there be a 2.0.7-final release? Both ecos-python and ecos have been stuck at 2.0.7rc2 since late April. Until a full release (not pre-release) is made on PyPI, `pip install ecos` won't work on Windows. I just tried both `pip install ecos` and `pip install ecos==2.0.7rc2` on Windows, and only the latter worked.

**Comment by echu** [comment]
There will be a final release. I'm waiting to collect some more data on it.
So far, it seems the installs have fixed a lot of the issues for Windows
users over the current version on pip. I'm likely paranoid, but wanting to
hold off on releasing until I really have time to man the issues.

If I had to estimate, let's put it in the November time frame. Thanks for
your patience!

**Comment by wkschwartz** [comment]
Thank you for the quick reply! I'll stay tuned.

**Comment by echu** [comment]
I just made a release for ECOS 2.0.7. `pip install -U ecos` should pick it up.
