### ISSUE TITLE
Conda packages for ECOS

### ISSUE THREAD

**Issue by mcg1969** [embotech/ecos-python#3]
Hey y'all, I built conda packages for ECOS-Python [here](https://anaconda.org/mcg/ecos). [Here](https://github.com/mcg1969/ecos-conda) is the Conda recipe that I'm using.

I know that you already have some conda support in your code, but I thought this might be helpful for you nonetheless. I have access to build workers for 32-bit & 64-bit windows, linux, and mac (minus 32-bit mac), which is nice, and I've got a webhook to anaconda.org to automatically rebuild when I update the recipe (though that isn't fully tested yet).

I thought you might find this useful. And of course, since I'm with Continuum now, if you need any help with conda and/or anaconda support, let me know.

**Comment by echu** [comment]
Thanks! This is awesome.

I've been using conda to make the Windows builds, but only to grab the wheels as a byproduct. There's a missing step of uploading to it to binstar.

Is there an external facing endpoint I could POST to to trigger the build on your machines (unless I misunderstood how the webhook works)? If there is, I could just POST a message to them and trigger the build on your workers for releases whenever the tests pass.

**Comment by mcg1969** [comment]
I'm not sure that will work, since as written the recipe itself has to be updated for each new version (and I wouldn't run it for dev builds, only tagged releases). I've been trying to see if there's an elegant way to build a static recipe that determines the version number. I'm pretty sure that's possible. If we did that, then the recipe could be triggered externally somehow.

**Comment by echu** [comment]
Ah. Got it. Well, if you do get that set up, that would be awesome. If not, we'll use email to coordinate releases. :)

**Comment by mcg1969** [comment]
Sure, that will work. I can update the script and trigger a build in no time. Moving forward, I may lobby to get ECOS moved to the main Anaconda channel.

**Comment by mcg1969** [comment]
For that matter you could do a pull request on the recipe.

**Comment by echu** [comment]
Ah! That's a good idea. We'll do just that.

**Comment by mcg1969** [comment]
Final comment! At some point, what we could do is have *you* (or cvxgrp, or whomever) take over the conda recipe repo, and I can simply point my Anaconda account to it.

**Comment by bollard** [comment]
Would be great if `2.0.7.post1` could be pushed up to Anaconda.[ Latest I can see is 2.0.5](https://anaconda.org/anaconda/ecos). Have to revert to `pip install ecos` for the time being. Thanks!

**Comment by h-vetinari** [comment]
A lot of progress has happened on the conda-forge side of the convex optimization ecosystem. Among other things, [cvxpy](https://github.com/conda-forge/cvxpy-feedstock), [cvxopt](https://github.com/conda-forge/cvxopt-feedstock), as well as the main solvers [ecos](https://github.com/conda-forge/ecos-feedstock), [osqp](https://github.com/conda-forge/osqp-feedstock), [scs](https://github.com/conda-forge/scs-feedstock) are current and published for all major OSes (some are even packaged for AArches).

Note that defaults considers conda-forge to be the "upstream" of recipes for almost all packages, and that the two channels are compiler-compatible since about a year or so. The conda-forge metadata already has 85k downloads for the package (and that's even though windows builds were just added a few days ago). All in all, I'm thinking that this issue can probably be closed.

**Comment by smerkli** [comment]
> All in all, I'm thinking that this issue can probably be closed.

Thanks to everyone involved for all their work! I'm closing the issue then.
